jwt:
  secret: AP/mTtG2INNS9nS/dz4kT+Lxo+Au4PhjfXE09zLKaZs=
  lifetime: 15m

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1018336611748-2p4r2h78p31gl0puv2ak0bpdtaavaacv.apps.googleusercontent.com
            client-secret: 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

youtube:
  clientId: 1018336611748-2p4r2h78p31gl0puv2ak0bpdtaavaacv.apps.googleusercontent.com
  clientSecret: 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
  redirectUri: http://localhost:3002/youtube/get-authorization-url

server:
  port: 3002

springdoc:
  swagger-ui:
    path: /api/docs
